// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chat

import (
	"super-agent/api/chat"
	"super-agent/internal/ai/agent/aiops"
	"super-agent/internal/logic/sse"

	agentchat "super-agent/internal/ai/agent/chat"

	"github.com/cloudwego/eino/compose"
	"github.com/cloudwego/eino/schema"
)

type ControllerV1 struct {
	service     *sse.Service
	runner      compose.Runnable[*agentchat.UserMessage, *schema.Message]
	aiopsRunner *aiops.Runner
}

func NewV1(
	runner compose.Runnable[*agentchat.UserMessage, *schema.Message],
	aiopsRunner *aiops.Runner,
) chat.IChatV1 {
	return &ControllerV1{
		service:     sse.NewSSE(),
		runner:      runner,
		aiopsRunner: aiopsRunner,
	}
}
